Commit Test BNR
HL-Cledor/algoStudy pull request #10
Opened 2021-11-16 12:33 UTC by BitnuriKim

First merge
commit test

2021-11-16 12:38 UTC, jeekim2 commented
리뷰어를 넣어보시게

2021-11-16 13:42 UTC, jeekim2 requested changes
파일명&폴더명 틀림. 문제번호랑 다르다.
저번 회의 때 얘기한대로, 해당 문제의 웹페이지 주소를 해당 파일 첫줄에 주석으로 넣으셔.

2021-11-16 13:44 UTC, Bobzzang commented
리뷰어 넣는 방법은 우측 상단에 "Reviewers" 항목에 톱니를 찾아보세용!

2021-11-17 09:35 UTC, jeekim2 approved these changes

2021-11-17 09:37 UTC, BitnuriKim commented
문제 번호 수정, 주석 추가, 리뷰어 추가 해서 push 했어요
여기 Pull requests에서 그대로 리뷰 하는건가여?

2021-11-17 09:55 UTC, jeekim2 commented
> 문제 번호 수정, 주석 추가, 리뷰어 추가 해서 push 했어요
> 
> 여기 Pull requests에서 그대로 리뷰 하는건가여?

ㅇㅇ 여기서 리뷰

2021-11-17 14:17 UTC, YHsla approved these changes
Cute!

2021-11-17 14:24 UTC, merged