YYH - daily commit 22.01.10
HL-Cledor/algoStudy pull request #111
Opened 2022-01-10 13:48 UTC by YHsla

2022-01-11 11:02 UTC, jeekim2 approved these changes
1152는... 공사다망하셨구먼..

2022-01-11 11:02 UTC, jeekim2 commented on Problems/5622/ans_5622_YH1.py
> +    time = len(char) # 시간은 각 문자에 해당하는 다이얼+1이기 때문에 한번에 먼저 계산.
아래 23번줄부터, dial의 숫자 개념이 들어가지 않는데
굳이 여기서 어렵게 만들 필요 있을지?
각 줄의 결과에서 1씩 더 넣어주면 됐을 것.
ex. 23번줄 : time+=3

2022-01-11 12:26 UTC, YHsla commented on Problems/5622/ans_5622_YH1.py
> +    char = input()
Character 이름 표현할 만한게 뭐가 있을까요.. 흠...

2022-01-11 12:37 UTC, YHsla commented on Problems/5622/ans_5622_YH1.py
> +            dial[i+2] = chr(start+3*i)+chr(start+3*i+1)+chr(start+3*i+2)
i=7일 경우는 PQRS를 나타내나는 거라 ord('S')로 83이 맞아요.

2022-01-11 12:37 UTC, YHsla commented on Problems/5622/ans_5622_YH1.py
> +                t+=k+1
의도한거는 이거였어요.
Dictionary로 dial을 저장하고, 2번 다이얼 - ABC, 3번 다이얼 - DEF 등등등..
그래서 range(8)에 key+2가 된거였습니다.
16번줄에 +1은 결국 다이얼 거는데 걸리는 시간이 (다이얼+1)이기 때문에 표현한거였습니다.
단순하다고 생각했는데.. 복잡하게 풀었나 보네요...

2022-01-11 12:37 UTC, YHsla commented on Problems/5622/ans_5622_YH1.py
> +    time = len(char) # 시간은 각 문자에 해당하는 다이얼+1이기 때문에 한번에 먼저 계산.
위의 풀이가 형이 얘기한대로의 접근이라서 다르게 함 해봤어요 이건..ㅋㅋ

2022-01-11 12:37 UTC, YHsla commented on Problems/5622/ans_5622_YH1.py
> +        elif  87 <= ord(x) and ord(x)<91 : time+=9
그러네..ㅋㅋ 뭔가 유니코드에 꽂혀서 써야겠다 하면서 쓴듯...ㅋㅋ

2022-01-11 14:42 UTC, jeekim2 approved these changes

2022-01-11 14:42 UTC, jeekim2 commented on Problems/5622/ans_5622_YH1.py
> +            dial[i+2] = chr(start+3*i)+chr(start+3*i+1)+chr(start+3*i+2)
> i=7일 경우는 PQRS를 나타내나는 거라 ord('S')로 83이 맞아요.

i값이 헷갈리니 리뷰도 헷갈려서 힘들구만...
i = 5 일 때 - 80, 81, 82, 83
i = 6 일 때 - 83, 84, 85 

즉 8번 다이얼에서 TUV가 아닌 STU 가 나옴.

2022-01-13 11:22 UTC, hongmyeong-lee commented on Problems/5622/ans_5622_YH1.py
> +            dial[i+2] = chr(start+3*i)+chr(start+3*i+1)+chr(start+3*i+2)
i+2 를 하나로 치환해서 쓰는게 보기더 좋았을듯
처음에 봤을 때는 왜 i = 5 or7을 굳이 따로 뺐는지 봤더니 알파벳이 7,9번에 4개 있어서 그런거였구만

2022-01-13 11:22 UTC, hongmyeong-lee commented on Problems/5622/ans_5622_YH1.py
> +        elif  87 <= ord(x) and ord(x)<91 : time+=9
꼭  풀이 할대 ord 안쓰고 dic 로 했어도 좋았을 듯

2022-01-19 08:20 UTC, jeekim2 commented on Problems/5622/ans_5622_YH1.py
> +    char = input()
@YHsla char가 별로라고 한 이유는, input() 가 character가 아니기 때문임.

2022-02-09 21:11 UTC, Bobzzang submitted a review, later dismissed
구현한 내용은 이해하는데 어렵지 않은데, 뭔가 data type 처리 등의 목적으로 한번 풀어봐야겠넹...

잘 배우고 갑니다!

2022-02-10 09:45 UTC, jeekim2 requested changes
solve() 로 안풀리는 이유에 대해 댓글 달았으니 수정 요망.

2022-02-28 13:39 UTC, YHsla commented
잘못된 풀이 삭제 완료

2022-03-04 10:40 UTC, jeekim2 approved these changes

2022-03-06 13:17 UTC, Bobzzang approved these changes

2022-03-15 13:37 UTC, merged