Daily commit 11399 lhm upload
HL-Cledor/algoStudy pull request #123
Opened 2022-01-16 02:21 UTC by hongmyeong-lee

2022-01-16 07:04 UTC, jeekim2 requested changes
Recursion error 회피 방안 고민을 해야겠지?

2022-01-16 08:15 UTC, YHsla submitted a review, later dismissed

2022-01-16 08:15 UTC, YHsla commented on Problems/11399/ans_11399_lhm.py
> +    return quick_sort(s1)+[pivot]+quick_sort(s2)
세미나 때에 설명한 시간복잡도 개념에서 위 표현은 Exponential complexity인 O(2N)임.
2의 N제곱으로 커지기 때문에 최대 회귀 호출 제한 1,000 (백준에서 정의한 제한치라고 함)을 넘어가게 됨.
퀵 소트에 대한 구현 방식을 변경하거나 다른 정렬 방식을 채택해보면 좋을 듯.

2022-01-16 13:04 UTC, Bobzzang approved these changes

2022-01-16 13:04 UTC, Bobzzang commented on Problems/11399/ans_11399_lhm.py
> +    return quick_sort(s1)+[pivot]+quick_sort(s2)
퀵 소트에서 pivot값에 따라 연산량이 달라질 수 있는거 아닌가?
현재 임의로 지정한 pivot의 값이 -1이 아닌 경우에는 좀더 줄어들 수 있는건 아닌지 궁금하넹.

2022-01-17 11:58 UTC, hongmyeong-lee commented on Problems/11399/ans_11399_lhm.py
> +    return quick_sort(s1)+[pivot]+quick_sort(s2)
다시 pivot 값을 중간값으로 바꾸니 해결됬네요 땡큐요

2022-01-20 09:44 UTC, BitnuriKim approved these changes

2022-01-24 11:47 UTC, Bobzzang approved these changes

2022-01-25 09:44 UTC, merged