Lhm
HL-Cledor/algoStudy pull request #14
Opened 2021-11-24 14:06 UTC by hongmyeong-lee

folder clean

2021-11-24 14:21 UTC, jeekim2 approved these changes
이전 PR 찾아보고 리뷰 달아준 내용 확인해보면 도움이 될 듯

2021-11-24 23:07 UTC, jeekim2 requested changes
1. 제대로 문제를 커버할수있게 답안을 정상적으로 수정(일부 케이스에 대해서 문제가 있어 그내용이 작성된걸로 보임)
2. 특정 input에서 문제가 있다면(그리고 직접 못잡을 것 같아서 도움이 필요하다면), 테스트 파일에 해당 케이스를 추가하고 push 한 후, Issue 작성해서 동료들에게 검토요청

2021-11-25 13:10 UTC, jeekim2 submitted a review, later dismissed
에러 난다는 부분이 무엇 때문인지 찾았으면 공유 요청합니다.

2021-11-25 13:10 UTC, jeekim2 commented on Problems/1712/1712.py
> +    print(int(a/(c-b))+1)
```suggestion
    print((a//(c-b))+1)
```
별거 아닌 것 같아도, type casting이 들어가게 되면 읽는 사람으로 하여금 그 안에 내용물이 원래 무엇이었는지
생각해보게 만드는 듯. 이미 a,b,c가 모두 integer 인 이상 불필요.

2021-11-26 14:02 UTC, jeekim2 requested changes
못풀었으면 Draft 처리

2021-11-26 23:26 UTC, jeekim2 requested changes
테스트 좀 해

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +    b = a.split()
```suggestion
b = int(input().split())
```
아래 코드 보니까 b만, 그것도 모든 element에 대해 integer casting 하면서 쓰던데
굳이 a를 할당하고, b도 string으로 놔둘 필요가 없음.

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +            print(2)
한 for 문 안에 input과 print를 한꺼번에 넣어도 백준을 통과하는지? (라고 적어놓고 제출 해보니 틀렸다 나오네.)
이렇게 하면 input 모두 받고 output 뿌리는게 아니라, input case 하나 입력 될 때마다 발생.

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +b =[]
아래에서 append 같은 method를 사용하지 않을 경우, 이런 초기화는 불필요

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +        break
for i in range(T) ==> i는 0부터 T-1까지 입력됨.
불필요 구문

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +    if (int(b[3])==int(b[0]))and (int(b[4])==int(b[1])):
두 지점인데, b를 변수를 쪼개서 썻으면 어떨지?
index 0 ~ 2, 3 ~ 5가 각각 쌍으로 비교되는 구문이 나오는데 알아보기 힘듦.

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +        a1 = max(((int(b[3])-int(b[0]))**2 + (int(b[4])-int(b[1]))**2)**0.5, int(b[2]),int(b[5]))
같은 계산의 반복인데, 따로 변수 분리 하는게 어떨지.

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +        a2 = a0.remove(a1)
반례
A = 0,0,5
B = 3,4,5

a0의 자료형이 set이므로 a0에서 5를 remove 하면서 싹 사라짐.

2021-11-26 23:26 UTC, jeekim2 commented on Problems/1002/1002.py
> +        a2 = a0.remove(a1)
위 반례와 별개로,
삼각형 성립 조건을 사용해서 풀려고 했던 것 같은데,
a0를 set을 사용했으면 remove가 아니라 a1도 set으로 정의한 후 차집합을 사용하는 것이 좋았을 것.
어쨋든, set을 사용 할 경우 이등변삼각형과 정삼각형 케이스에서 원소가 3개 미만이 되는 것에 주의.

2021-11-26 23:32 UTC, jeekim2 commented
실패한 문제 Push 하려거든 draft 처리를 합시다

2021-11-27 04:40 UTC, hongmyeong-lee commented on Problems/1712/1712.py
> +    print(int(a/(c-b))+1)
네 불필요한 code를 지우는 습관을 들이겠습니다

2021-11-27 05:36 UTC, hongmyeong-lee commented on Problems/1002/1002.py
> +            print(2)
이거 넣고 돌렸을 때 50%까지는 통과하고 그 뒤에 fail한 걸 봐서는 test case가 다 만족되지 못해서 그런 거 같음 경우의 수가 부족해서 그런거 같은데 도저히 어디가 빠졌는지 잘 모르겠음...

2021-11-27 09:05 UTC, jeekim2 commented
1. commit 제목은 채팅이 아님.
2. 고려했던 case가 무엇이었는지 알 수 없으니, 반례를 찾아주기가 어려움. Test 파일을 올리면 도와줄수 있을지도?
3. PR draft 안하는 이유는?

2021-12-03 16:25 UTC, jeekim2 commented
현재 PR에 올라온 파일들 모두 성공 한 것인지?? 안됐다면 주석을 달든 이슈를 쳐놓든 관리를 해줄것.

2021-12-05 09:52 UTC, Bobzzang approved these changes
Problem 2798의 경우, 백준에서 성공하는거 확인하였음.

2021-12-05 09:52 UTC, Bobzzang commented on Problems/2798/2798.py
> +                result = sum
Num 숫자가 늘어날수록 모든 조건을 타도록 설정되어 있음.
따라서 For에 의한 run time을 줄이기 위한 방법을 추가하는게 어떨지.

2021-12-05 09:52 UTC, Bobzzang commented on Problems/2798/2798.py
> +    for j in Num:
```suggestion
for i in (0,len(Num)-2):
    for j in (i+1,len(Num)-1):
```
위에처럼 index를 이용하고, 첫번째 카드(i)를 뽑았을 때 2번째/3번째 카드는 굳이 비교 대상이 되지 않아 For에서 비교할 필요가 없어짐. 따라서, 이렇게 하면 run time 시간이 줄어들 수 있어 보임.

2021-12-06 11:56 UTC, jeekim2 requested changes
리뷰를 해줘도 정작 작성자가 안보면 의미가 없다

2021-12-07 12:02 UTC, jeekim2 requested changes
아직 안풀린 문제가 있어서 approve를 줄 수가 없다.

2021-12-07 12:02 UTC, jeekim2 commented on Problems/11653/11653.py
> +        list.append(num)
이 줄 때문에 9번줄 pop(-2)를 하는 것 같은데, 이런식으로 구현 한 이유가 있나..?
5, 9번 줄 지우고 해도 통과는 하는거같은데.

2021-12-07 12:02 UTC, jeekim2 commented on Problems/11653/11653.py
> +        Calc(num, list)
재귀를 돌리는데, 어째 내가 푼 방법보다 더 빠르다...왜지...

2021-12-10 10:23 UTC, jeekim2 requested changes

2021-12-10 10:23 UTC, jeekim2 commented on Problems/programmers_hash_1/42576.py
> +'''
이렇게 하면 아마 안될텐데? 굳이 날려버리고 푼 이유는?

2021-12-10 10:25 UTC, jeekim2 requested changes
완료되지 않은 내용은 추가 표시 필요

2021-12-11 13:30 UTC, Bobzzang commented on Problems/programmers_hash_2/phonenumber.py
> +#startswith 모르면 풀기 어렵다
startswitch() / endswitch()
- str 타입일 경우, 시작되는 단어 혹은 끝나는 단어를 비교하여 확인 가능함.

str type이 아닌 숫자만을 비교하는 경우에도 사용이 안될 것으로 보입니다.

2021-12-11 13:40 UTC, jeekim2 requested changes
1002, 1110 여전히 안풀림.

2021-12-11 13:40 UTC, jeekim2 commented on Problems/programmers_hash_2/phonenumber.py
> +#startswith 모르면 풀기 어렵다
https://github.com/HL-Cledor/algoStudy/pull/33

문제의 목적(hash)에 맞지 않게 푼 것 같아, 새로 풀어본 내용 올림.

2021-12-11 13:40 UTC, jeekim2 commented on Problems/1002/1002.py
> +            print(2)
이거 여전히 완료 안됨.

2021-12-11 13:40 UTC, jeekim2 commented on Problems/1110/1110.py
>  #https://www.acmicpc.net/problem/1110
메모리 초과 에러 발생함. 완료 확인하고 앞으로 어떻게 할 것인지 답변요

2021-12-11 13:40 UTC, jeekim2 commented on Problems/1110/1110.py
> +in1 = inputVal/10   #2
이러면 유리수가 될텐데?

2021-12-11 13:40 UTC, jeekim2 commented on Problems/2231/2231.py
> +    A = list(map(int,str(i)))
무시무시한 반복을....
풀리는건 확인했다만, 효율적인 풀이를 고민해봐야 하지 않을지.

2021-12-11 13:40 UTC, jeekim2 commented on Problems/3009/3009.py
> +
노가다성 ㅗㅜㅑ...

풀어보진 않았다만, counter를 잘 활용하면 어떻게 되지 않을까 싶음.

2021-12-11 13:40 UTC, jeekim2 commented on Problems/4153/4153.py
> +    A.remove(B)
remove 너무 좋아하는듯.

sort 혹은 sorted 활용하는 방법은 어떨지?

2021-12-11 13:42 UTC, jeekim2 requested changes

2021-12-11 13:42 UTC, jeekim2 commented on Problems/programmers_hash_1/42576.py
> +#좋은 답변
내가 쓴 코멘트 보고 쓴 주석인 것 같은데,
소통은 github에서 하고 주석은 해당 문제의 설명이나 강조 필요한 내용에 집중하는 것이 어떨지.

2021-12-11 14:22 UTC, Bobzzang commented on Problems/1002/1002.py
> +        a1 = max(((int(b[3])-int(b[0]))**2 + (int(b[4])-int(b[1]))**2)**0.5, int(b[2]),int(b[5]))
b = int(input().split()) 이걸로 받았기 때문에, int로 꼭 처리할 필요는 없지 않을까?

그리고 b[0]/[1]/[2]/[3]/[4]는 가독성이 좀 떨어지는 듯하여, x1/y1/x2/y2/r로 함수내 변수 설정하는게 다른 사람들이 이해하기 쉬울 듯.

2021-12-11 14:22 UTC, Bobzzang commented on Problems/1002/1002.py
> +            print(2)
**_(반례)_**
r = 0인 경우, '-1' (무한대의 경우 발생)하는 조건이 필요하지 않을까?

2021-12-13 11:21 UTC, jeekim2 requested changes
여전히 댓글을 보지 않는다.

2021-12-13 11:21 UTC, jeekim2 commented on Problems/programmers_array_2/42746.py
> +# *3을 하면 각 자리수에 대한 최대값을 알 수 있게 됨
되게 어려운 string 비교 특성을 사용한건데, 진짜 이해하고 쓴거 맞는지?
(주석의 설명이 그 특성을 반영하지 않음)
string *3을 한다면 해당 string을 세번 반복한 것이 출력되게 될테고,
각 string끼리 대소비교를 하면 앞 "character"부터 ascii 번호비교를, 
"순차적으로" 하게 되는 특성을 이용한 것 같은데...
의도한 풀이라면 파이썬 공부 많이 한 것이겠지만 그닥 가독성 있는 코드는 아니라는 개인적 생각.
(string을 저런식으로 대소비교 하는 것이 딱히 권장되는 형태나, 사용되는 형태가 아닌지라...)

2021-12-20 13:23 UTC, hongmyeong-lee commented on Problems/programmers_array_2/42746.py
> +# *3을 하면 각 자리수에 대한 최대값을 알 수 있게 됨
해당 내용은 도저히 모르겠어서 다른사람이 푼거 보고 이해하려고 노력한다음에 써본거에요
string 반복해서 대소 비교도 할 수 있는 게 다른데 쓰기 좋은 듯 합니다.

2021-12-21 11:59 UTC, hongmyeong-lee commented on Problems/programmers_array_1/42748.py
> +print(solution([1, 5, 2, 6, 3, 7, 4],[[2, 5, 3], [4, 4, 1], [1, 7, 3]]))
반영하였습니다.

2021-12-21 12:00 UTC, hongmyeong-lee commented on Problems/programmers_hash_1/42576.py
> +#좋은 답변
해당 내용 반영 앞으로는 주석은 설명에 집중하도록 하겠습니다.

2021-12-21 12:01 UTC, hongmyeong-lee commented on Problems/4153/4153.py
> +    A.remove(B)
네 향후에는 반영하도록 하겠습니다.

2021-12-21 12:04 UTC, hongmyeong-lee commented on Problems/3009/3009.py
> +
아직 외부 모듈이나 라이브러리 활용하는게 익숙하지 않아서
from collections import counter
counter(array)  
이러한 방식으로 쓰는게 어색하네요..
몇개 외워서 쓰면 정말 편할 듯 합니다.

2021-12-21 12:07 UTC, hongmyeong-lee commented on Problems/2231/2231.py
> +    A = list(map(int,str(i)))
해당 문제가 비가역적? 으로 풀기가 좀 어려워서 하나씩 trial &error 와 같은 방식으로 접근했네요..
해보진 않았지만 재귀적 용법을 활용하면 괜찮은 방법이 나올 수 있을 듯 합니다.

2021-12-21 12:08 UTC, hongmyeong-lee commented on Problems/1110/1110.py
> +in1 = inputVal/10   #2
저거 주석 처리 했을텐데요 일단 최신걸로 다시 업로드 하겠습니다.

2021-12-21 12:42 UTC, jeekim2 requested changes
파일이 너무 많이 쌓였다...리뷰가 넘 어렵네.

2021-12-21 12:42 UTC, jeekim2 commented on Problems/3009/3009.py
> +
그런 카운터 얘기가 아니라 우리 로직 짤때 쓰는 그냥 카운터 올리는거..

2021-12-21 12:42 UTC, jeekim2 commented on Problems/Mando_codingTest/temp3.py
> +from typing import no_type_check
이건 뭐지

2021-12-21 12:42 UTC, jeekim2 commented on Problems/Mando_codingTest/temp3.py
> +print(solution([6, 1, 6, 6, 7, 5, 6, 7]))
여전히 테스트케이스와 답안이 구분되지 않음.

2021-12-21 12:42 UTC, jeekim2 commented on Problems/1110/1110.py
> +in1 = inputVal/10   #2
반영 어디..?

2021-12-21 12:42 UTC, jeekim2 commented on Problems/programmers_array_1/42748.py
> +print(solution([1, 5, 2, 6, 3, 7, 4],[[2, 5, 3], [4, 4, 1], [1, 7, 3]]))
어디..?

2021-12-21 12:42 UTC, jeekim2 commented on Problems/programmers_stack_2/42587.py
> +print(solution([2, 1, 3, 2],2))
이것도 테스트 케이스 분리 요망

2021-12-21 12:42 UTC, jeekim2 commented on Problems/programmers_stack_4/42584.py
> +    return result
다른사람 풀이를 굳이 올려야하나 싶네
이건 다음 모임때 의견 검토

2021-12-21 13:02 UTC, hongmyeong-lee commented on Problems/1110/1110.py
>  #https://www.acmicpc.net/problem/1110
수정해서 올렸습니다.

2021-12-21 13:06 UTC, jeekim2 requested changes
설마 이것만 있다고 생각하는거 아니지..?

2021-12-21 13:07 UTC, jeekim2 requested changes

2021-12-21 13:07 UTC, jeekim2 commented on Problems/programmers_array_1/42748.py
> -print(solution([1, 5, 2, 6, 3, 7, 4],[[2, 5, 3], [4, 4, 1], [1, 7, 3]]))
설마 이것만 있다고 생각하는거 아니지..?

2021-12-21 13:24 UTC, hongmyeong-lee commented on Problems/1002/1002.py
> +            print(2)
수정했습니다. 예전에도 이거 수정해서 올렷던거 같은데 왜 반영이 안되어있는거 같지...

2021-12-21 13:27 UTC, hongmyeong-lee commented on Problems/programmers_hash_1/42576.py
> +'''
이거 지금 풀려잇는거 올라가 있을 건데 다시 확인좀

2021-12-21 13:32 UTC, hongmyeong-lee commented on Problems/11653/11653.py
> +        list.append(num)
코드의 효율성을 보면 그럴 수 있는 소인수 분해라는 거 자체가 본 수부터 시작해서 그렇게 해놓은거 같네요 저도 오랜만에 보니..

2021-12-21 13:33 UTC, hongmyeong-lee commented on Problems/2798/2798.py
> +    for j in Num:
아 좋은 생각이네요 이거 코드 썻을 당시에는 for문 돌리는거에 대해 제한 둘 생각을 못했어요
보기 더 이쁜? or 정형화 된? for문을 기계적으로 쓰다보니..

2021-12-21 13:34 UTC, hongmyeong-lee commented on Problems/2798/2798.py
> +                result = sum
형이 아래 쓴데로 for문 자체에 조건을 넣는 게 좋을 듯 합니다.

2021-12-21 13:35 UTC, hongmyeong-lee commented on Problems/1002/1002.py
> +        a2 = a0.remove(a1)
해당 문제는 고쳐서 업로드 하였습니다.

2021-12-21 13:36 UTC, hongmyeong-lee commented on Problems/1712/1712.py
> +    print(int(a/(c-b))+1)
이거 첨에 불필요하게 for문을 겁나 많이 돌려서 run time error 뜬다고 말했던거 같네요

2021-12-21 13:44 UTC, jeekim2 requested changes
TC 분리반영만 하고 덮읍시다... 남이 푼거는 일단 그대로 두고...
다음부터는 PR 분리해서 올려주길.

2021-12-21 13:44 UTC, jeekim2 commented on Problems/1110/1110.py
>  #https://www.acmicpc.net/problem/1110
확인완료

2021-12-21 13:44 UTC, jeekim2 commented on Problems/Mando_codingTest/temp2.py
> +print(solution([1,2,3],[2,3,4],[3,4,65]))
TC 분리 반영필요

2021-12-21 13:44 UTC, jeekim2 commented on Problems/Mando_codingTest/temp4.py
> +print(solution([-1,-3,6,1,2,4]))
TC 분리 반영 필요

2021-12-21 13:44 UTC, jeekim2 commented on Problems/programmers_완전탐색_3/42842.py
> +#실제문제는 yellow 값이 가로 세로 각각 2개를 뺀 것과 같게 해야됨
이것도, 남이 푼거 올릴지 여부 검토 필요..

2021-12-21 13:49 UTC, hongmyeong-lee commented on Problems/Mando_codingTest/temp2.py
> +print(solution([1,2,3],[2,3,4],[3,4,65]))
tc 제거완

2021-12-21 13:50 UTC, hongmyeong-lee commented on Problems/Mando_codingTest/temp4.py
> +print(solution([-1,-3,6,1,2,4]))
tc 제거완

2021-12-21 13:53 UTC, hongmyeong-lee commented on Problems/programmers_stack_2/42587.py
> +print(solution([2, 1, 3, 2],2))
1110 다른 풀이로 올렸는데?

2021-12-21 14:10 UTC, jeekim2 approved these changes

2021-12-22 03:32 UTC, Bobzzang approved these changes
이제 그만 merge 해보자. 고생 많으셨으요.

2021-12-22 03:32 UTC, Bobzzang commented on Problems/Mando_codingTest/temp3.py
> +from typing import no_type_check
좀 찾아보니 아래와 같이 설명이 되어 있네요.

"현재 typing 모듈에 존재하는, 함수나 클래스에서 형 검사 어노테이션을 완전히 비활성화하는 no_type_check 기능"
(Ref. https://docs.python.org/ko/3/library/typing.html)

근데, 아래 문제를 푸는데 왜 필요한지는 모르겠습니다...

2021-12-23 05:26 UTC, merged