220126_Dailycommit_1932_BNR
HL-Cledor/algoStudy pull request #149
Opened 2022-01-26 07:33 UTC by BitnuriKim

답은 맞는데 시간초과...

2022-01-26 10:16 UTC, hongmyeong-lee commented on Problems/1932/ans_1932_BNR.py
> +
이 부분 때문에  runtime error가 뜨는거 같은데 i, j를 써서 여기서 시간 복잡도가 올라가는 듯?
i 하나만 쓰는 방안 고려해야 할듯

2022-01-26 20:28 UTC, YHsla submitted a review, later dismissed

2022-01-26 20:28 UTC, YHsla commented on Problems/1932/ans_1932_BNR.py
> +TA= [list(map(int, sys.stdin.readline().split())) for _ in range(N)]
입력부에 대한 한줄 표기 인상 깊음.

2022-01-26 20:28 UTC, YHsla commented on Problems/1932/ans_1932_BNR.py
> +        dp[i][j] = max(dp[i-1][j-1]+TA[i][j], dp[i-1][j]+TA[i][j])
귀납적 접근에 대한 주석 추가 good

2022-01-27 13:03 UTC, jeekim2 requested changes
Python3로도 풀리는 문제임.
실제로 돌려보니 시간초과가 아닌 RunTime error네.

2022-01-28 01:49 UTC, BitnuriKim commented
Run Time Error 고쳐서 다시 Commit 했습니다.
N==1, N==2일 때 리턴값 설정을 안해줘서 나온 오류입니다. 리뷰해주세요~

2022-01-28 09:36 UTC, jeekim2 approved these changes
로직에 이견은 없으나, 함수로 작성하는 방법을 연습해보면 좋을듯.

2022-01-29 01:59 UTC, BitnuriKim commented
담부턴 함수로 푸는 연습할게여

2022-02-08 21:46 UTC, Bobzzang approved these changes
나도 전에 이렇게 유사하게 fail이 되는 경험이 있어..

N=1, N=2일 경우와 같은 다양한 Case를 고민하지 않고 문제에 주어진 Test case는 패스했는데 왜 fail이지...진짜 별거 아닌데 반례를 생각해내지 못해서 삽질을 엄청 했었지요...

이래서 test case를 만들고 돌려보는 걸 해봐야 하는거 같아요!

2022-02-09 15:10 UTC, BitnuriKim commented
N이 0,1인 조건을 빼먹을 때가 있더라구요ㅠ 테스트의 중요성!

2022-02-09 15:10 UTC, merged