YYH - daily commit 22.01.28
HL-Cledor/algoStudy pull request #156
Opened 2022-01-27 19:03 UTC by YHsla

2022-01-28 10:03 UTC, jeekim2 approved these changes
다들 Dynamic programming 을 풀 때 Bottom-up과 Top-down을 따로라고 생각하는데,
(이 문제에서처럼, 아예 방법을 나눠버린게 자주 목격됨)
둘은 본질적으로 하나이고, 경우에 따라서 그 접근 방식을 나눌 수 있다고 봄.
이 문제에서처럼, 최종 N에 대한 값을 구하기 위해서 N 미만의 "모든" 계산이 최소 1회 씩 필요한 경우(계산 횟수를 줄일 수 없는 경우) Bottom up이 효과적이고 (더이상 계산 횟수를 줄일 수 없으므로), 재귀 횟수 제한까지 걸려있느니만큼 Bottom up으로 풀게 될 것임.

그러나, 문제 및 그 점화식에 따라서는 N의 값을 구하는데 N 미만의 모든 계산이 필요하지 않은 경우가 있고 (ex. f(n) = f(n//2) + f(n//2-1) 등), 이런 경우에는 Bottom up은 쓸데없는 계산까지 해야 하는 Brutal force 가 됨. Top Down인 경우에는 계산 횟수가 매우 단축되겠지... 그러나 이것을 Bottom-up으로 구한다고 해서, 답이 나오지 않는 것은 아님
(모든 경우가 계산되며 올라가니, 언젠가는 나오겠지)

즉슨, DP1 문제 세트가 대부분 Bottom up으로 풀리는 점화식(N 이하 모든 경우를 계산해야하는), 재귀 제한에 걸리는 input 갯수의 문제로 구성되어있긴 하지만, 그렇다고 이걸 나누어서 생각 할 필요는 없다는 것임.

본 문제에서도, dp 함수를 top down 재귀로 풀리도록 디자인을 해 두고,
재귀 제한이 걸린다면 따로 구문을 짤 것이 아니라, 해당 dp 함수를 아래에서부터 순차적으로 호출 해 주면 되는 것임 (내가 푼 대부분의 DP 문제 접근이 이런식).

2022-01-29 18:47 UTC, YHsla commented on Problems/11726/ans_11726_YH.py
> +        if n not in memo:
딕셔너리로 해야하는데.. 무심코 리스트로 한듯..
그래서 Recursion error가 발생된건가..

2022-02-11 08:49 UTC, Bobzzang approved these changes
Dynamic Programming도 방식은 유사한 구조를 가지는거 같아요.
이견 없으며 Approve 합니다.

2022-02-11 12:02 UTC, jeekim2 requested changes
comment 확인 후 재리뷰.
solve2로는 시간초과가 나오는 것 같네 (Recursion error도 아니고..).
삭제하든, 의도했던대로 풀어보든 하세염.

2022-02-27 13:59 UTC, YHsla commented
재풀이해서 올림

2022-02-28 08:27 UTC, jeekim2 approved these changes

2022-03-03 17:34 UTC, Bobzzang approved these changes

2022-03-15 13:36 UTC, merged