Daily commit 2630 lhm upload
HL-Cledor/algoStudy pull request #170
Opened 2022-02-01 02:17 UTC by hongmyeong-lee

2022-02-01 02:26 UTC, jeekim2 requested changes
문제번호 주석 빠짐

2022-02-01 02:26 UTC, jeekim2 commented on Problems/2630/ans_2630.py
> +print(result.count(1))  # 파랑종이
이렇게 할거였으면, result[2] 로 선언해서 각각 21, 23번줄에서 value+=1 해주면 됐지 않았을까?

2022-02-03 00:59 UTC, hongmyeong-lee commented
다 바꿨심다

2022-02-03 13:05 UTC, jeekim2 approved these changes

2022-02-03 18:58 UTC, YHsla approved these changes
분할 정복 구조화 잘한 듯~~

2022-02-08 20:46 UTC, merged