YYH - Problem 9012
HL-Cledor/algoStudy pull request #191
Opened 2022-02-09 21:14 UTC by YHsla

2022-02-10 09:30 UTC, jeekim2 requested changes
정상적으로 열리고 닫힌 괄호는 더이상 의미가 없다라는 점에 착안을 하면
stack을 이용한 출제 의도에 맞는 풀이가 나올 것임.
더 생각해보세여.

2022-02-10 09:30 UTC, jeekim2 commented on Problems/9012/ans_9012_YH.py
> +            elif x == ')' and '(' not in stack:
in~ not in~ 은 마법의 주문이 아님. 결과적으로 리스트를 순회하면서 있는지 찾아내는거거든.
여기서 시간 손실이 필연적이고,
이 문제를 푸는 핵심 구문이 여기긴 한데 출제의도와 맞지 않는 것 같음.

2022-02-12 21:43 UTC, hongmyeong-lee commented on Problems/9012/ans_9012_YH.py
> +            elif x == ')' and '(' not in stack:
근데 괄호 여부를 in, not in이 아니라 if a==b?? 이렇게 보면 시간 손실이 줄어드는 건가요?
기본적으로 문제를 stack으로 푼건 잘한 거 같습니다.

2022-02-13 05:09 UTC, jeekim2 commented on Problems/9012/ans_9012_YH.py
> +            elif x == ')' and '(' not in stack:
> 근데 괄호 여부를 in, not in이 아니라 if a==b?? 이렇게 보면 시간 손실이 줄어드는 건가요? 기본적으로 문제를 stack으로 푼건 잘한 거 같습니다.

x in list 는 list의 인자 중 x 가 있는지를 확인하는 것임.
stack은 탐색을 지원하는 자료구조가 아니기때문에, 이런식으로 탐색을 돌렸다는건 stack을 이용해서 푼게 아님.

2022-02-13 21:44 UTC, YHsla commented on Problems/9012/ans_9012_YH.py
> +            elif x == ')' and '(' not in stack:
형이 힌트해준 방법으로 재 풀이해봤어요!(solve3)
처음에 왜 stack 풀이인지를 감을 못잡았는데.. 형 힌트 덕에 잡았습니다.
감사 감사~

2022-02-14 07:41 UTC, jeekim2 approved these changes

2022-03-07 08:54 UTC, BitnuriKim approved these changes

2022-03-15 13:36 UTC, merged