Daily commit - YYH
HL-Cledor/algoStudy pull request #21
Opened 2021-12-01 13:33 UTC by YHsla

To be continued...

5가지 정렬 방식(선택, 버블, 삽입, 병합, 퀵)에 대해서 세미나 해볼까 함..
Python의 sort는 Tim sort라고 해서 삽입과 병합 정렬 아이디어에서 착안했다고 하는데..

아직 공부 중...

2021-12-07 12:03 UTC, jeekim2 commented
님 Draft 걸어두면 리뷰를 못해여

2021-12-08 13:17 UTC, Bobzzang reviewed
Review 가능한 듯한데?

2021-12-08 13:18 UTC, Bobzzang commented
> 님 Draft 걸어두면 리뷰를 못해여

daily commit 누르면 들어가면 Review 가능한 듯 한데요?

2021-12-08 13:22 UTC, jeekim2 commented
> 

그러넹
낼 해야지... 야근힘들..

2021-12-11 13:48 UTC, jeekim2 requested changes
2751번 풀이는 읽기 편하게 하기 위해 주석 풀어주세요.

2021-12-11 13:48 UTC, jeekim2 commented on Problems/2751/ans_2751.py
> +import sys
고생 많이 했는데,
함수 구현이 제대로 된거면 그냥 주석 풀어놓고,
맨 아래 if __name__=="__main__": 에서 풀이가 성공하는 함수를 call 하는 식으로 하면 어떨지.
주석과 함수 구현 내용이 구분이 안되서 어렵넹

2021-12-11 13:48 UTC, jeekim2 commented on Problems/10870/ans_10870_YH.py
> +    result = fibonacci(n-1)+fibonacci(n-2)
기본적인 피보나치 풀이법 OK

연관 문제에 N 이 큰 경우에 대해서도 있으니, 풀어보면 동적계획법에 대해 공부하는데 도움이 될거임.

2021-12-12 14:29 UTC, YHsla commented on Problems/10870/ans_10870_YH.py
> +    result = fibonacci(n-1)+fibonacci(n-2)
동적계획법... Keyword 기억해두었다고 공부해보겠습니다!
피보나치가 Exponential complexity 라는 걸 오늘 알게 됐음..ㅋ

2021-12-12 14:29 UTC, YHsla commented on Problems/2751/ans_2751.py
> +import sys
사실 저 아래 5가지 정렬 모두 Failed입니다....  Heap정렬이나 Shell 정렬로 해야 문제가 Passed될 것 같은데.. 
5개 정렬도 머리에 집어넣는데 과부하라....추후에 추가적으로 보강해서 올릴 수 있도록 하겠습니다.
PR draft가 너무 길어지고 있어서 일단 세미나용이라 생각해서 PR 수행했습니다.

2021-12-13 10:39 UTC, jeekim2 commented on Problems/2751/ans_2751.py
> +import sys
ㅇㅇ 문제 상에서는 fail이 맞을 텐데,
정렬 로직 구현 자체가 잘못된게 아니니, 문제풀이용으로 Pass하는 함수만 call 하면 되지 않겠냐는것.
다른 정렬 로직을 보고싶은데 주석이 걸려있어서 검토가 어렵네.

2021-12-14 14:14 UTC, YHsla commented on Problems/2751/ans_2751.py
> +import sys
이 파일은 그대로 두고 Seminar 용으로 내용 정리해서 별도의 파일 올렸습니다. 그거 참고해주세요

2021-12-15 13:24 UTC, jeekim2 approved these changes

2021-12-15 13:24 UTC, jeekim2 commented on Problems/9663/ans_9663_YH.py
>  # 시간초과 발생
https://github.com/HL-Cledor/algoStudy/pull/41

참조... 이건 Python으로 안되는게 맞지 싶당

2021-12-16 11:23 UTC, jeekim2 requested changes
N-Queen 은 어쩌실?

2021-12-18 04:34 UTC, YHsla commented on Problems/9663/ans_9663_YH.py
>  # 시간초과 발생
넵.. 이건 pypy3로는 가능은 하다는데...  Python으로 가능 여부를 미리 알아볼 방법이 있을까요?

2021-12-18 04:35 UTC, YHsla commented on Problems/1003/ans_1003_YH.py
> +# 최적화 필요
ㅇㅇ 알고 있음. Draft로 빼서 동적 계획법 공부해서 다시 도전하겠음

2021-12-18 06:20 UTC, YHsla reviewed
PR승인 고고~~

2021-12-18 06:22 UTC, YHsla commented on Problems/9663/ans_9663_YH.py
>  # 시간초과 발생
일단 PyPy3로 통과 확인~

2021-12-19 01:54 UTC, jeekim2 approved these changes
고생여

2021-12-19 11:34 UTC, Bobzzang approved these changes
고생 많으셨습니다.

Sort에 대한 다양한 방법과 설명이 나와있네용. 많은 공부가 되었어요!

세미나 떄를 기대하겠숩니다ㅎㅎㅎ

2021-12-19 12:48 UTC, merged