220330_DailyCommit_10871_BNR
HL-Cledor/algoStudy pull request #276
Opened 2022-03-30 10:15 UTC by BitnuriKim

2022-03-30 12:10 UTC, jeekim2 requested changes
문제번호 변경 요

2022-03-30 12:10 UTC, jeekim2 commented on Problems/10871/ans_10871_BNR.py
> +https://www.acmicpc.net/problem/12852
문제번호 틀림

2022-04-01 04:43 UTC, BitnuriKim commented on Problems/10871/ans_10871_BNR.py
> +https://www.acmicpc.net/problem/12852
변경 했습니다~

2022-04-05 10:01 UTC, jeekim2 approved these changes

2022-04-08 11:10 UTC, Bobzzang approved these changes
풀이는 간단해서 이견 없습니다!.! 수고하셨어용~~

2022-04-08 13:18 UTC, merged