Daily commit - 11279_LHM2
HL-Cledor/algoStudy pull request #291
Opened 2022-04-07 11:29 UTC by hongmyeong-lee

2022-04-09 14:32 UTC, jeekim2 requested changes
기본적인 heap 동작에 맞게 구현을 한 것 같으나,
전역변수 리스트를 사용하면서 그걸 다시 파라메터로 전달하면서 코드가 너무 너저분.

2022-04-09 14:32 UTC, jeekim2 commented on Problems/11279/11279_ans_lhm2.py
> +    priority_queue.pop()
전역변수를 자꾸 쓰니까 이런 이상한 코드가 나오지...
queue == priority_queue 아닌가.

2022-04-26 11:14 UTC, hongmyeong-lee commented on Problems/11279/11279_ans_lhm2.py
> +    priority_queue.pop()
이게 queue에 대한 변수를 다 하나로 해도 됨
이게 이전에 있는 queue에다가 값을 수정해서 넣는 다는 개념으로 이름을 다르게 했던 거 같음

2022-04-26 11:46 UTC, jeekim2 reviewed
queue는 분명 전역변수인데,
어디서는 파라메터로 넘겨받고,
어디서는 전역변수니 직접 갖다 쓰고,
선언은 스크립트 중 가장 아래에 있고...
정리를 좀 해봅시다.

2022-07-13 11:22 UTC, merged