Problem 10869
HL-Cledor/algoStudy pull request #3
Opened 2021-11-09 13:56 UTC by YHsla

10869 Problem

2021-11-10 09:08 UTC, jeekim2 requested changes
Request changes 기능 확인용 Review 결과

2021-11-10 13:50 UTC, YHsla commented on 10869.py
> +num = input();
Thank you. I haven't finished studying Python's internal function yet.
I will try it based on your advise.

2021-11-11 14:35 UTC, jeekim2 approved these changes
It seems nice try to resolve by class.

2021-11-13 13:22 UTC, Bobzzang commented on 10869.py
> +num = input();
A, B = map(int(input().split(" "))) 이부분에서
A, B를 구분하기 위해서는 " "를 사용하는 것도 나중에 넣은 input을 구분하는 것에 용이하지 않을까요?

추가로, 
A, B = map(int(input().split()))
(뒤에 문제 중에 A,B 숫자 비교 문제에서도 동일한 형태를 사용하고 있습니다.)

2021-11-13 13:22 UTC, Bobzzang approved these changes
Good

2021-11-13 13:23 UTC, Bobzzang approved these changes

2021-11-13 13:26 UTC, Bobzzang approved these changes

2021-11-13 13:28 UTC, Bobzzang approved these changes

2021-11-13 14:04 UTC, merged