Daily Commit on 2022.04.14 : Problem 10816 Binary search - Card find #2
HL-Cledor/algoStudy pull request #309
Opened 2022-04-14 14:33 UTC by Bobzzang

답은 정상적으로 나오는데 시간 초과가 발생되네요..해당 방법에 대한 수정을 해보고 PR 변경하도록 하겠습니다.

2022-04-17 11:41 UTC, Bobzzang commented
이분탐색을 사용하려고 했지만...시간초과가 계속 되서 dictionary랑 for를 사용하니 문제가 풀리더라고요...

이분 탐색 해결방식으로 접근했을 때에는, 제가 while과 for를 같이 쓴 것이 시간 초과를 일으킨 원인으로 보여지네요.

2022-04-18 10:41 UTC, jeekim2 requested changes
확인요

2022-04-18 10:41 UTC, jeekim2 commented on Problems/10816/ans_10816_JHP.py
> +            return card_list[start:end+1].count(target)
return 이 이 문장밖에 없으니,
target 과 같은 카드가 없는 경우 무한루프를 탈 것이고 그러면 시간초과가 뜨겠지
시간복잡도에 의한 시간초과가 아닐 것 같다

2022-04-18 10:41 UTC, jeekim2 requested changes
확인요

2022-04-19 12:44 UTC, Bobzzang commented on Problems/10816/ans_10816_JHP.py
> +            return card_list[start:end+1].count(target)
형이 말한대로 이진탐색 문제에서 원하는 값이 없었을 때에 시간초과가 발생할 수 있겠더라고요. 
그래서 단순하게 while  바깥쪽에 return None을 추가해봤는데 그래도 답은 나와도 시간초과가 계속 뜨더라고요...

결국 좀 찾아보니, Lower/Upper Bound algorithm을 사용하는 방법에 대해 알게 되었고 해당 알고리즘으로 문제를 풀었을 때 이진 탐색법을 활용해서 문제 해결이 가능했습니다.

상세 내용은 코드 다시한번 리뷰 해주시면 감사 드리겠습니다!

2022-04-22 12:24 UTC, jeekim2 reviewed
Binary search 자체에는 별 이견 없음. 구현의 형태가 깔끔하게 정리된 듯.
Boundary 처리하는 구문에서 이상한 분기문이 있는데 확인요

2022-04-22 12:24 UTC, jeekim2 commented on Problems/10816/ans_10816_JHP.py
> +        if ans != None:
이 구문이 거짓이 될 수 있나? ans는 integer 밖에 안될 것 같은데..

2022-04-24 12:14 UTC, Bobzzang commented on Problems/10816/ans_10816_JHP.py
> +        if ans != None:
그러네요. 
주어진 숫자 array에 원하는 숫자가 없을 때, 값이 없을 수도 있는 경우를 생각했던건데 실제로는 불필요하네요.

해당 내용 수정하여 업데이트 하겠습니다.

2022-04-24 20:00 UTC, jeekim2 approved these changes

2022-04-27 14:17 UTC, hongmyeong-lee approved these changes

2022-04-27 14:17 UTC, hongmyeong-lee commented on Problems/10816/ans_10816_JHP.py
> +            return card_list[start:end+1].count(target)
upper bound/lower bound에 대한 내용을 몰랐었는데 이걸 보고 알았네요
기존 이진탐색에서 배열을 3영역으로 나눠 탐색하는 방법인거 같은데
upper bound/lower bound는 A,B 영역을 비교하는데 A,B의 길이가 둘다 클때 쓰면 좋겠군요

2022-04-27 14:50 UTC, merged