20211214 daily commit
HL-Cledor/algoStudy pull request #40
Opened 2021-12-14 13:52 UTC by Bobzzang

이게 답은 다 나오는데, 왜 "틀렸습니다"가 뜨는지....잘 모르겠습니다.

아무리 봐도 잘 모르겠어서, Help를 쳐봅니다....

2021-12-15 10:39 UTC, jeekim2 requested changes
디버깅 할 때 브레이크 포인트 걸어놓고 무지성 F5 누르면 이런거 못잡음

2021-12-15 10:39 UTC, jeekim2 commented on Problems/1018/ans_1018_JHP.py
> +        result.append(first_W)
```suggestion
            result.append(first_B)
            result.append(first_W)
```

파이썬에서 다중 반복문을 걸면 머리아파지는 이유...
indent-rainbow extension을 씁시다.

2021-12-19 11:29 UTC, Bobzzang commented
원인 분석 및 해결 완료되어 PR 업데이트 합니다.

2021-12-19 11:31 UTC, Bobzzang commented on Problems/1018/ans_1018_JHP.py
> +        result.append(first_W)
Rainbow extension을 사용했는데...append가 다중 루프를 돌리다보니 i에 대해 update하는 걸로 잘못 생각하고 짰더라고요....로직 자체는 맞는 접근이었으나 휴먼 에러였습니다....

2021-12-20 11:26 UTC, jeekim2 approved these changes

2021-12-22 11:36 UTC, hongmyeong-lee commented on Problems/1018/ans_1018_JHP.py
> +        result.append(first_W)
Rainbow extension이 어떤걸 말하는거에요?

2021-12-23 11:18 UTC, jeekim2 commented on Problems/1018/ans_1018_JHP.py
> +        result.append(first_W)
> Rainbow extension이 어떤걸 말하는거에요?

저저번 세미나 때 소개 했던 VS Code extension 중 하나

2021-12-23 13:17 UTC, YHsla approved these changes
고생하셨습니다!

2021-12-24 12:18 UTC, merged