7568 lhm
HL-Cledor/algoStudy pull request #59
Opened 2021-12-24 11:40 UTC by hongmyeong-lee

2021-12-24 12:15 UTC, BitnuriKim approved these changes

2021-12-25 02:01 UTC, jeekim2 requested changes
파일 위치 이동 부탁합니다. 지금도 폴더가 너무 많아서 어떻게 관리해야할지 고민 필요.
ex. Problems/7568/7568_lhm.py

2021-12-25 02:01 UTC, jeekim2 commented on Problems/7568_lhm/7568.py
> +    print(count)
백준에서는 이렇게 줘도 통과한 것 같은데, 정확한 출력 Format과 다름.
```suggestion
    print(count,end=" ")
print()
```

2021-12-25 13:12 UTC, YHsla submitted a review, later dismissed

2021-12-25 13:12 UTC, YHsla commented on Problems/7568_lhm/7568.py
> +T = int(input())
문제에 대한 주소는 첫줄에 주석으로 추가하기로 협의된 사항으로 준수 필요!

2021-12-25 13:12 UTC, YHsla commented on Problems/7568_lhm/7568.py
> +    ans.append((w,h))
ans보단 result 추천..ㅋㅋ 도찐개찐이지만..ㅋㅋ

2021-12-25 13:12 UTC, YHsla commented on Problems/7568_lhm/7568.py
> +    print(count)
14번에 print()는 왜 하는거에요?

2021-12-25 13:33 UTC, hongmyeong-lee commented on Problems/7568_lhm/7568.py
> +T = int(input())
파일 위치 어디로 옮길까요

2021-12-25 13:43 UTC, hongmyeong-lee commented on Problems/7568_lhm/7568.py
> +    print(count)
저건 그냥 답변 표시하려고 하는거고 end를 붙여야 좀더 정확한 답변양식인듯

2021-12-25 13:46 UTC, hongmyeong-lee commented on Problems/7568_lhm/7568.py
> +                count = count +1
10번이 아니라 11번 줄 말하는 건가요

2021-12-25 13:46 UTC, hongmyeong-lee commented on Problems/7568_lhm/7568.py
> +    ans.append((w,h))
향후에 고려하도록 하겠습니다
별 생각 없이 썻네요...

2021-12-26 02:57 UTC, jeekim2 commented on Problems/7568_lhm/7568.py
> +T = int(input())
> 파일 위치 어디로 옮길까요

ex 썻잖음

2021-12-26 02:59 UTC, jeekim2 requested changes

2021-12-26 02:59 UTC, jeekim2 commented on Problems/7568_lhm/7568.py
> +                count = count +1
> 10번이 아니라 11번 줄 말하는 건가요

1번줄 추가 했으니 11번이 된거겠지

2021-12-26 22:24 UTC, jeekim2 approved these changes

2022-01-03 10:54 UTC, hongmyeong-lee commented
이건 왜 밑에 merge가 없는거지.. approval 좀 부탁드립니다. 폴더위치 변경다 예전에 했습니다.

2022-01-08 10:31 UTC, Bobzzang approved these changes
이견 없어 Approve 합니다.

2022-01-09 11:48 UTC, merged