11650 lhm
HL-Cledor/algoStudy pull request #65
Opened 2021-12-27 03:19 UTC by hongmyeong-lee

2021-12-28 01:55 UTC, Bobzzang requested changes
앞에 #63 PR부터 merge하고 해결해주세요.

Branch 사용하는 방법은 나도 그렇고 모두가 좀 정리가 필요해 보이네요ㅠㅠ

2022-01-03 10:50 UTC, hongmyeong-lee commented
#63 PR merge 완료하였습니다.
더불어 해당 문제를 sort() 없이 해결하려고 할 때, min/max 를 이용하여 풀었는데 백준에서 돌릴때 시간 초과가 뜨는 군요
혹시 왜그런지 아시는분

2022-01-03 11:48 UTC, hongmyeong-lee commented
이건 다시 해보겠습니다

2022-01-03 12:13 UTC, hongmyeong-lee commented
문제 다시 풀어 봤는데 시간 초과가 왜 뜨는지 몰겠어요 ㅜ

2022-01-03 14:04 UTC, jeekim2 commented
> 문제 다시 풀어 봤는데 시간 초과가 왜 뜨는지 몰겠어요 ㅜ

왜냐면 시간복잡도가 높기 때문이지 (교환정렬 - O(N^2))
정렬을 공부 안하고 들이대면 대가리가 깨집니다 공부하세요

2022-01-05 08:15 UTC, jeekim2 commented
@hongmyeong-lee 해결 안된 것은 draft 처리요
내가 일단 draft 돌려놨는데 확인 바람.

2022-01-05 13:23 UTC, hongmyeong-lee commented
이거 sort 말고는 못풀겠네요 ㅜㅜ
배열로는 답이 없어보여서 아래로 해봤는데 그래도 시간초과 뜸
딴사람들이 다 푼거 봐도 sort로만 품
#https://www.acmicpc.net/problem/11650
import sys
input = sys.stdin.readline
T = int(input())
temp = []
ans = []


for i in range(T):
    [x,y] = map(int,input().split())
    temp.append([x,y])

while len(temp)>0:
    ans.append(min(temp))
    temp.remove((min(temp)))


for i in range(len(ans)):
    print(ans[i][0], ans[i][1])

2022-01-06 11:46 UTC, hongmyeong-lee commented
quick sort 로 하니까 되네요 pivot으로  sort하는게 첨보는 개념이어서 신기하네요
구글 좀 참조해서 했습니다
시간 복잡도가 낮아서 통과했네요

2022-01-06 12:06 UTC, jeekim2 approved these changes

2022-01-06 12:06 UTC, jeekim2 commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
i, pivot의 형태는 [x, y] 일건데 이걸 비교연산자로 넣었을때 어떤식으로 작동하는지 확실히 파악하고 쓴것인지??

2022-01-06 12:06 UTC, jeekim2 commented on Problems/11650/11650_lhm.py
> +    [x,y] = map(int,input().split())
```suggestion
    x,y = map(int,input().split())
```
별 의미없는 list 묶음

2022-01-06 12:06 UTC, jeekim2 commented on Problems/11650/11650_lhm.py
> +ans = []
마지막에서 ans를 set하므로 필요없는 구문

2022-01-06 12:17 UTC, hongmyeong-lee commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
pivot을 기준으로 작은 값을 왼쪽, 큰 값을 오른쪽에 넣는 걸로 실제 비교 하는 건 값이고 넣는 건 위치로 알고 있습니다.

2022-01-06 12:21 UTC, hongmyeong-lee commented on Problems/11650/11650_lhm.py
> +ans = []
말한거 다 반영했습니다

2022-01-06 12:29 UTC, jeekim2 commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
@hongmyeong-lee 
[1,4] < [2,3] : True/False?

[1,3] < [2,4] : True/False?

[1,5,3] < [2,2,4] : True/False?

위 세 문제에 대해 답이 직관적으로 나온다?

2022-01-06 12:30 UTC, jeekim2 approved these changes
리뷰 지적 내용에 대해 Approve 했다면 반영은 안해도 됨.
반영하면서 Approve 풀려서 귀찮거든

2022-01-06 12:44 UTC, hongmyeong-lee commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
배열의 길이가 짝수일 경우 오른쪽이 피벗 값이고 홀수의 경우 가운데가 피벗 값인데
피벗 왼쪽에 있는 값 부터 비교하게 되니가 형이 말하는 문제의 답은
T/T/T 아닌가요?

2022-01-06 12:57 UTC, jeekim2 commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
ㅇㅇ 순차적으로 비교해나가는 내용을 알고 의도한거냐는 의미
대소비교가 어떻게 동작할지 명확하지 않으면 읽기 어려운 코드가 됨.

2022-01-06 13:16 UTC, hongmyeong-lee commented on Problems/11650/11650_lhm.py
> +        if i < pivot : less_arr.append(i)
향후 고려 하겠습니다

2022-01-06 13:40 UTC, Bobzzang approved these changes

2022-01-06 13:41 UTC, merged