15649 lhm baekjoon
HL-Cledor/algoStudy pull request #67
Opened 2021-12-28 02:36 UTC by hongmyeong-lee

2021-12-28 05:23 UTC, jeekim2 approved these changes
Study의 목적을 생각 해 보셔.
Python package를 많이 알고 잘 쓰겠다! 가 너의 목적이라면 그것에 맞춰서 리뷰 하겠음.

2021-12-29 03:12 UTC, Bobzzang approved these changes
문제가 백트레킹으로 해결하는 것으로 되어있기 때문에 백트레킹 알고리즘으로 해결하길 권장합니다.
특히, N,M문제를 이해하면 이후에 DFS 및 BFS 등의 향후 탐색 알고리즘에도 이해하는데 많은 도움이 되기 때문에 제대로 백트래킹으로 풀어보는걸 추천해용!

2022-01-01 14:51 UTC, jeekim2 requested changes
이 PR에 Feedback 있을 때까지 CR로 변경

2022-01-02 14:02 UTC, hongmyeong-lee commented
DFS 로 했습니다.
깊이탐색이라는 걸 첨봤네요.. 구글 좀 참조해서 이해하는 위주로 진행했습니다.
추후에는 알고리즘 위주의 풀이를 하도록 노력하겠습니다.
DFS라는 것이 재귀와 stack을 같이 쓰는 것을 의미하기도 하나 보네요

2022-01-02 14:10 UTC, jeekim2 commented
> 

오개념 방지를 위해 comment.
DFS는 탐색의 개념일 뿐임.
그 구현 방법 중 이 문제에 사용할 수 있는 방법으로 재귀와 stack을 이용하는 방법이 있는 것

2022-01-02 14:10 UTC, jeekim2 submitted a review, later dismissed
확인완료

2022-01-05 08:34 UTC, jeekim2 commented
ans_15649_lhm.py 에 의해 conflict 발생

2022-01-05 10:34 UTC, hongmyeong-lee commented
error 뜬거 우선 다른 파일명으로 해서 다시 올렸습니다.
이전꺼는 1이고 변경한게 2입니다.

2022-01-05 10:36 UTC, jeekim2 commented
> error 뜬거 우선 다른 파일명으로 해서 다시 올렸습니다. 이전꺼는 1이고 변경한게 2입니다.

conflict fix가 안됨.
fetch & merge 상태 확인

2022-01-05 10:42 UTC, hongmyeong-lee commented
confilct 재확인 부탁드립니다

2022-01-05 10:46 UTC, hongmyeong-lee commented
다시 fetch 체크해봤습니다 확인좀요

2022-01-05 10:57 UTC, jeekim2 approved these changes
conflict가 발생하면, 해당 PR 최하단 (merge 아이콘 뜨는 부분)에 나타남.

2022-01-07 12:21 UTC, Bobzzang approved these changes

2022-01-07 12:21 UTC, Bobzzang commented on Problems/15649/ans_15649_lhm2.py
> +        dfs()#재귀
이렇게 해도 가능하겠구나...배워가봅니다ㅎㅎㅎㅎ
난 index를 항상 받아서 index를 항상 올려주면서 재귀를 돌렸는데,
arr.append를 사용하니 바로 len(arr)를 사용해도 되서 코드가 심플해지네.

2022-01-08 02:58 UTC, jeekim2 approved these changes

2022-01-09 11:46 UTC, merged