Daily commit - 211114
HL-Cledor/algoStudy pull request #7
Opened 2021-11-14 14:56 UTC by YHsla

2021-11-15 12:23 UTC, jeekim2 requested changes
파일 위치 조정요

2021-11-15 12:23 UTC, jeekim2 commented on 2562.py
> +while i < 9:
for문이 더 이쁘지 않나? 개취..

2021-11-15 12:23 UTC, jeekim2 commented on 2562.py
> +    num_max = max(num_max, num_list[i])
input 갯수가 길어지면, max 찾는데 매 iteration 마다 시간 증가할 것.

2021-11-15 12:23 UTC, jeekim2 commented on 2562.py
> +    if num_max == num_list[i]:
num_list 대신 num_val을 그대로 썻다면?

2021-11-15 12:23 UTC, jeekim2 commented on 2562.py
> +print("%d\n%d"%(num_max, max_order))
```suggestion
print(num_max)
print(max_order)
```

2021-11-15 13:30 UTC, Bobzzang submitted a review, later dismissed

2021-11-15 13:30 UTC, Bobzzang commented on 2562.py
> +while i < 9:
개인적으로 저렇게 되는 경우엔, for i in range(N) 형태가 더 좋은 듯해요.

Python 교육 들었을 때, 대부분 while은 "while True:"로 지속적으로 동작되도록 설정하고, break를 쓰는 경우가 대부분이었습니다.

while을 쓴다면...

while True:
    num_val = int(input())
    num_list.append(num_val) 
    num_max = max(num_max, num_list[i])
    if i == len(num_list):
        break
   i = i +1

이런식으로 쓰는 방법도 있지 않을까요?

2021-11-15 13:39 UTC, YHsla commented on 2562.py
> +while i < 9:
while 한번 써보고 싶어서 넣어본건데 for문이 더 낫긴 한것 같음

2021-11-15 13:41 UTC, YHsla commented on 2562.py
> +    num_max = max(num_max, num_list[i])
증가할거라는 우려?? max 찾는 방식을 더 효율적으로 접근하라는 건가요?

2021-11-15 13:43 UTC, YHsla commented on 2562.py
> +    if num_max == num_list[i]:
그대로 쓴다면 보기 쉬운 것 외에 이득이 있을까요?

2021-11-15 13:50 UTC, jeekim2 commented on 2562.py
> +    if num_max == num_list[i]:
보기 쉬운건 지고의 가치 아닌가.....ㅋㅋㅋㅋ
iterator를 넣었다는건 뭔가 저 구문이 iteration 상 중요해야 할 것 같은데, 그런 구문은 아닌 것 같음.

2021-11-15 23:08 UTC, jeekim2 commented
CR 발행했었는데 추가커밋 올라오니 결과가 없어지는구만
(관련 설정 걸어놨는데, 그것때문인듯함)
PR 있는상태에서 push 했으면, Review request를 재요청해야할것같음.

2021-11-15 23:09 UTC, jeekim2 submitted a review, later dismissed

2021-11-16 07:24 UTC, Bobzzang submitted a review, later dismissed

2021-11-17 14:21 UTC, YHsla commented on 2562.py
> +    num_max = max(num_max, num_list[i])
오키 running 측면으로도 고려해보겠음

2021-11-17 14:24 UTC, jeekim2 requested changes
2447 conflict  resolve 바랍니다.

2021-11-17 14:24 UTC, jeekim2 commented on Problems/1065/ans_1065_y1.py
> +            if ((int(str_i[0])-int(str_i[1]))==(int(str_i[1])-int(str_i[2]))):
```suggestion
            str_i = list(map(int,list(str(i))))
            if str_i[0]-str_i[1]==str_i[1]-str_i[2]:
```
자주 쓰는 string 숫자 integer list로 분해 방법

2021-11-18 06:44 UTC, Bobzzang submitted a review, later dismissed
Please update the change request and review opinion.

2021-11-20 13:02 UTC, jeekim2 requested changes
이 commit 과 별개로, merge conflict 예정되어있으므로 해당 내용 변경 필요

2021-11-20 13:02 UTC, jeekim2 commented on Problems/1929/ans_1929.py
> +            prime_list[2*i::i] = [False]*(N//i-1)
for문 처리가 이해하기 어려웠음.
```suggestion
for i, v in enumerate(prime_list):
    if i*i > N:
        break
    if v:
        prime_list[2*i::i] = [False]*((N+1//i)-1) 
```
List slicing은 좋은 기능이긴 하다만, 이런식으로 set 하는 방식으로 사용하면
갯수가 맞지 않을 경우에 대해서 고려를 해야 함.
알고리즘 상, N//i -1 을 했어도 유효 input 범위 안에서 어쨋든 false가 나오기 때문에 괜찮았지만,
len(prime_list) == N+1 이므로 알고리즘에 따라서는 error 발생 할 수 있어보임.
list slicing은 reference로만 사용하는게 좋은 것 같다는게 내 결론인데,
다른 사람들은 어떻게 쓰는지 잘 모르겠네.

2021-11-20 13:38 UTC, Bobzzang commented on Problems/2292/ans_2292.py
> +    print(GoToRoom(Num))
GoToRoom을 Unit Test에서 호출하면 아마 test 불가능하지 않을까요?
만일 하려고 한다면, Num = int(input())을 GoToRoom으로 넣어야 할 듯합니다.

또한, pow 함수를 이용하여 알고리즘 도출 방법에 대해 추가로 설명해주면 좋을거 같습니다.
(pow(base : int/float, exp: int/float, mode = None) # returns int or float depending on whether exp is non-negative)

현재 코드에서는, 3*MIN^2 + 3*MIN 으로 구현되어 있는데
- MIN이 1인 경우, 3+3 = 6
- MIN이 2인 경우, 3*2^2+3*2 = 18
- MIN이 3인 경우, 3*3^2 + 3*3 = 36
- MIN이 4인 경우, 3*4^2 + 3*4 = 60 

제가 숫자를 세면서 알고리즘으로는, 
- 1번 방은 6(6*1)개 방과 접촉
- 2~7번 방은 18(6*3)개 방과 접촉
- 8~19번 방은 30(12*2개 + 모서리 6개*1)개 방과 접촉
- 20~37번 방은 42(18*2개 + 모서리 6개*1)개 방과 접촉
--> 즉, number of room * 2 + 6으로 항상 늘어나는 것으로 보여짐.

이해한 알고리즘적인 차이가 있는것 같아 추가로 문의 드립니다!ㅎㅎㅎ

2021-11-21 14:20 UTC, jeekim2 requested changes
Conflict resolve는 왜안하는거임

2021-11-21 14:20 UTC, jeekim2 commented on Problems/2447/ans_2447_y1.py
> +        print(i)
Unit test case 작성 고려해보길

2021-11-22 14:27 UTC, jeekim2 requested changes
Resolve Conflict !!!!!

2021-11-22 14:27 UTC, jeekim2 commented on Problems/1929/test_1929.py
> +    assert Problem_1929(2, 20) == print("2","3","5","7","11","13","17","19", end="\n")
print문 출력 비교 이렇게 가능하면 test case 만들기 좋겠네.
근데 문제 내용을 Ctrl+A 해서 제출했을 때, 해당 내용이 Pass 되는지?

2021-11-23 13:48 UTC, jeekim2 approved these changes

2021-11-24 12:21 UTC, YHsla commented on Problems/1065/ans_1065_y1.py
> +            if ((int(str_i[0])-int(str_i[1]))==(int(str_i[1])-int(str_i[2]))):
홀... 신박... 감사..ㅋㅋ

2021-11-24 12:22 UTC, YHsla commented on Problems/1929/ans_1929.py
> +        if is_prime[i]:print(i)
맞음.. if __name__ == "__main__" 특징이 뭔지 모르고 따라 쓴 거라 Unit test 생각 못하고 한거..
앞으론 Unit test 병행해서 문제 풀도록 하겠음!

2021-11-24 12:33 UTC, YHsla commented on Problems/2292/ans_2292.py
> +    print(GoToRoom(Num))
1. Unit test 고려 못함..( if name == "main" 특징이 뭔지 모르고 따라 했었던 거라 Unit test 생각 못함)
2. 2**3과 같은 표현을 몰라서 pow() 내장 함수 사용했던 건데 알고리즘 도출 방법 확인해서 공유토록 하겟음!
3. 재현이가 써준 내용이 정확히는 이해가 안가는데.. 같은 원리로 보고 있는 듯함.. 결국엔 등차 6인 수열의 합 형태로 증가하는 규칙이 있어 등차수열의 합 일반식 적용해서 푼 문제임!

2021-11-24 12:38 UTC, YHsla commented on Problems/1929/ans_1929.py
> +            prime_list[2*i::i] = [False]*(N//i-1)
enumerate 함수 이용한 갯수 고려하는 방법 확인! 감사~

2021-11-24 12:39 UTC, YHsla commented on Problems/2447/ans_2447_y1.py
> +        print(i)
1. 앞으로 Unit test case 고려해보겠음
2. Conflict resolve는 죄송..ㅠ

2021-11-24 12:42 UTC, YHsla commented on Problems/1929/test_1929.py
> +    assert Problem_1929(2, 20) == print("2","3","5","7","11","13","17","19", end="\n")
1. 처음에 문제 풀 때 Unit test 고려 없이 풀었고, Unit test 처음 시도해볼 겸 1929 문제 선택해서 돌렸음.
2. 당연히 Unit test 풀 수 있는 형태로 안되어 있어서 ans_1929를 변경함(unit test 연습용으로 변경해서 풀어봄)
3. 결론적으로 변경 전은 pass이나 변경 후는 non pass임.

2021-11-24 12:59 UTC, Bobzzang approved these changes
Conflict resolved. Possible to Approve :)

2021-11-24 14:21 UTC, merged