15650 lhm
HL-Cledor/algoStudy pull request #70
Opened 2021-12-29 05:34 UTC by hongmyeong-lee

2021-12-29 07:48 UTC, jeekim2 requested changes
#67 에 대해 Comment 답변 전까지 Change request 처리

2022-01-02 14:42 UTC, hongmyeong-lee commented
#67 에 대한 답변 완료 하였고 15650 문제도 유사한 방식으로 풀었습니다

2022-01-02 15:08 UTC, jeekim2 submitted a review, later dismissed

2022-01-05 08:33 UTC, jeekim2 commented
conflict 해결하세여

2022-01-05 10:42 UTC, hongmyeong-lee commented
confilct 재확인 부탁드립니다

2022-01-05 10:56 UTC, jeekim2 approved these changes
뭔가 이상한 방식으로 conflict를 해제한것같지만... 일단 merge부터 합시다.. 확인이 너무 어렵네 하도 많아서

2022-01-06 12:34 UTC, BitnuriKim approved these changes

2022-01-06 12:34 UTC, BitnuriKim commented on Problems/15650/ans_15650_lhm2.py
> +        arr.pop()
재귀형태라 위에서 다시 함수 call할텐데 이부분은 왜 필요한 건가요..?

2022-01-06 13:19 UTC, jeekim2 commented on Problems/15650/ans_15650_lhm2.py
> +        arr.pop()
@BitnuriKim arr.pop()을 묻는거라면, 재귀를 마치고 돌아가서 그 다음 element를 가져오게 하기 위함.
문제 예시 2번을 보면, 1 2 / 1 3 / 1 4 형태로 나오는 것을 알 수 있는데,
1을 그대로 두고, 2, 3, 4 순차적으로 넣었다 뺏다 하면서 재귀 깊이마다 수열이 길어짐.
물어보는게 이게 맞는지 모르겠군

2022-01-06 13:38 UTC, BitnuriKim commented on Problems/15650/ans_15650_lhm2.py
> +        arr.pop()
맞아요 pop이 이해안갔는데 설명 감사합니다!

2022-01-09 11:45 UTC, merged