10773 lhm
HL-Cledor/algoStudy pull request #73
Opened 2021-12-30 03:27 UTC by hongmyeong-lee

2021-12-30 13:42 UTC, YHsla approved these changes

2021-12-30 13:42 UTC, YHsla commented on Problems/10773/10773.py
> +for i in range(T):
i에 대한 사용이 없고 단순 반복을 위한 for 문의 경우,
for _ in range(T) 형태로 많이 쓰는 듯.
MISRA에 지적될 사항일지는 모르나 i보다는 위의 표현으로 하는게 더 좋을 것 같음.

2021-12-30 13:42 UTC, YHsla commented on Problems/10773/10773.py
> +    x = int(input())
이건 질문.
한번에 Array로 입력받아서 사용하는 방식과 위와 같이 반복문 cycle마다 입력받는 방식이
메모리 등에서 차이가 있는가? (간략히 찾아볼 때는 차이가 없는 듯한데...)

2021-12-30 13:42 UTC, YHsla commented on Problems/15649/ans_15649_lhm.py
> +b = list(permutations(a,y))
permutation에 대한 구현도 생각해보길...

2021-12-30 13:42 UTC, YHsla commented on Problems/15649/ans_15649_lhm.py
> +        print(b[i][j], end=" ")
이게 백준에서 통과 됨?
의도된 출력이 안나오는 것 같은데...

2021-12-30 13:42 UTC, YHsla commented on Problems/15650/ans_15650_lhm.py
> +        print(temp2[i][j])#, end=" ")
이것도 의도된 출력이 안나올것 같은데..???

2021-12-31 05:45 UTC, jeekim2 commented on Problems/10773/10773.py
> +for i in range(T):
> i에 대한 사용이 없고 단순 반복을 위한 for 문의 경우,
> for _ in range(T) 형태로 많이 쓰는 듯.
> MISRA에 지적될 사항일지는 모르나 i보다는 위의 표현으로 하는게 더 좋을 것 같음.

_ 로 하는건 내 스타일인데? 누구 다른사람 그렇게 쓰더나

2021-12-31 05:54 UTC, jeekim2 requested changes
CR
1. 이전 PR의 commit이 계속 쌓이고 있음.
2. 이전 PR(#67 )에서 리뷰 요청 주안점에 대해 Feedback 없음.

2021-12-31 05:54 UTC, jeekim2 commented on Problems/10773/10773.py
> +    x = int(input())
> 이건 질문.
> 한번에 Array로 입력받아서 사용하는 방식과 위와 같이 반복문 cycle마다 입력받는 방식이
> 메모리 등에서 차이가 있는가? (간략히 찾아볼 때는 차이가 없는 듯한데...)

Input을 모두 누적시킨 후 중간중간에 있는 0과 그 앞의 값을 remove나 Pop 등으로 날려버리는 경우에 대한 질문이라면(원본 수정),
0 뒤의 내용에 대해 당겨쓰는 시간이 발생 하기 때문에 시간 소요가 발생 할 것 (뒤의 길이가 길면 길수록 시간이 오래걸림).
뭐 이런 부분은 input data와 output data를 분리해서 쓰면 문제 없을 것으로 보임 (input 식별 후 output에 옮겨적기)

2021-12-31 05:54 UTC, jeekim2 commented on Problems/15649/ans_15649_lhm.py
> +        print(b[i][j], end=" ")
백준 TC가 완벽하게 포맷 매칭을 확인하진 않는듯.
모양 틀린게 맞음.

2022-01-02 14:43 UTC, hongmyeong-lee commented on Problems/10773/10773.py
> +for i in range(T):
보면 그렇게 쓰는 사람 가끔봤음

2022-01-02 14:43 UTC, hongmyeong-lee commented on Problems/15649/ans_15649_lhm.py
> +b = list(permutations(a,y))
이것도 해서 올렸어요

2022-01-02 15:10 UTC, jeekim2 approved these changes

2022-01-03 10:55 UTC, merged