10828 lhm
HL-Cledor/algoStudy pull request #77
Opened 2021-12-31 01:11 UTC by hongmyeong-lee

2021-12-31 06:01 UTC, jeekim2 approved these changes
10828 제외 나머지 리뷰 내용은 다른 PR에 있음.
이 PR이 가장 최신인 듯 하므로 Approve
이후 추가로 PR이 분리되지 않은 채 올라오면 이 PR은 RC 처리하겠음.

2021-12-31 09:53 UTC, YHsla approved these changes
몇몇 문제가 리뷰했던 것 같은데 또 있군..

2021-12-31 09:53 UTC, YHsla commented on Problems/10828/10828.py
> +    stack.pop(-1)
for 반복문 내에서 입력을 받다보니 기능 흉내만 있고 Stack의 역할은 없는 듯함.
n번째 요소와 n-3번째 요소에 대한 연산을 하고 싶다고 하면 위 코드로는 어려울듯.

2022-01-02 11:43 UTC, jeekim2 requested changes
#85 가 신규로 올라왔으므로 CR 처리

2022-01-02 14:46 UTC, hongmyeong-lee commented on Problems/10828/10828.py
> +            out.pop(-1)
-1 쓸필요가 없다는 얘기군요

2022-01-02 14:46 UTC, hongmyeong-lee commented on Problems/10828/10828.py
> +    stack.pop(-1)
위 문제에 대해서만 고려했고 영한이형 케이스는 고려하지 못했네요

2022-01-08 04:05 UTC, jeekim2 approved these changes

2022-01-09 11:46 UTC, merged