Lhm
HL-Cledor/algoStudy pull request #8
Opened 2021-11-15 11:13 UTC by hongmyeong-lee

2021-11-15 11:15 UTC, hongmyeong-lee commented
review please

2021-11-15 12:09 UTC, jeekim2 requested changes
파일 위치 변경 요망

2021-11-15 12:09 UTC, jeekim2 commented on LHM/Problems/beakjoon/1110.py
> +input.insert(1,in2)
What if in1 was list? Then the sentence 10 can't be work properly.
```suggestion
input.assert(in1)
input.assert(in2)
```

2021-11-15 12:17 UTC, jeekim2 requested changes

2021-11-15 12:17 UTC, jeekim2 commented on LHM/Problems/beakjoon/1110.py
> +in1 = math.floor(inputVal/10)   #2
```suggestion
in1 = inputVal//10
```
The operator // can return the quotient only (useful during integer calculation)

2021-11-15 12:17 UTC, jeekim2 commented on LHM/Problems/beakjoon/1110.py
> +#https://www.acmicpc.net/problem/1110
이거 진짜 1110 문제 맞는지? 뭔가 아닌거같음.

2021-11-15 12:17 UTC, jeekim2 commented on LHM/Problems/beakjoon/1110.py
> +input.insert(1,in2) #6
in1 이 list 라면, insert(1,in2) 가 제대로 안 먹을 것 (in1의 1번에 삽입됨).
append 가 적절할 것으로 보임

2021-11-15 12:17 UTC, jeekim2 commented on LHM/Problems/beakjoon/15552.py
> +for i in range(0,T):
```suggestion
for i in range(T):
```
better

2021-11-15 12:17 UTC, jeekim2 commented on LHM/Problems/beakjoon/2884.py
> +H2 = math.floor(Time_min_2/60)
```suggestion
H2 = Time_min_2//60
```

2021-11-15 13:33 UTC, Bobzzang reviewed
현재 ㅅㅌㄷ랑 관계 없는 파일이 첩자로 들어와 있는듯 한데...의도한건지 확인 부탁 드려용!

2021-11-15 13:50 UTC, YHsla commented on LHM/Problems/beakjoon/10951.py
> +    a, b = map(int, sys.stdin.readline().split())
1. sys import해서 sys.stdin.readline() 통해 input을 받아오는 걸로 보이는데... 이거 활용하는 이점이 있는지?(몰라서 묻는거임)
2. while문에 대해 break 없이 벗어날 수 있음?

2021-11-15 13:55 UTC, YHsla commented on LHM/Problems/beakjoon/2588.py
> +ans2 = input1*(math.floor((input2%100)/10))
math 없이 풀어보는 방향 고려~~

2021-11-15 14:04 UTC, jeekim2 commented on LHM/Problems/beakjoon/10951.py
> +    a, b = map(int, sys.stdin.readline().split())
1번에 대한 대답 : input 함수보다 sys.stdin.readline이 더 빠름. input은 줄바꿈 문자 같은걸 처리해준다고 하는데, 나도 안해봐서. 설명해놓은 자료는 인터넷에 많더이다.

2021-11-15 14:06 UTC, jeekim2 commented on LHM/Problems/beakjoon/10951.py
> +    a, b = map(int, sys.stdin.readline().split())
while 자체가 필요가 없네

2021-11-16 13:31 UTC, jeekim2 commented
해결되지 않은 것(개발 중)을 올리려거든, PR을 닫아놓는 것도 방법일 듯.
맨 아래 Close Pull request 이용.

2021-11-17 15:04 UTC, jeekim2 commented
그는 코멘트를 보지않는듯하다

2021-11-19 23:11 UTC, jeekim2 commented
언제쯤 코멘트를 볼것인가

2021-11-19 23:20 UTC, jeekim2 requested changes
1. 완료못한 문제를 올리려거든 파일 수준에서 표시를 해둡시다.
2. 경로좀 맞췄으면 좋겠는데..
3. 해결 못한 문제를 올려놓고 다른문제를 풀다가 그것도 해결 못한걸 올린다는건 GG쳤다는걸로 보이는데, 그렇다면 GG친 문제를 어떻게 처리할것인지? 문제풀어서 올리는 상황이 아니라 협업 개발 프로젝트상에서 맡은 모듈이 해결안되는 상황이라 가정하고 처리했으면 좋겠음.

2021-11-22 14:31 UTC, jeekim2 requested changes
여전히 경로를 지키지 않음.

2021-11-22 14:31 UTC, jeekim2 commented on LHM/Problems/beakjoon/2577.py
> +    if List[i]=='9':
List[i]=='0' 인 경우, 아래 if 문을 모두 검사하면서 필요 없는 수행 시간을 잡아먹게 될 것.
elif (else if) 의 사용을 고려해보든지 (이것도 '9'인 경우 앞에 분기문을 모두 검사해야 하니 비추..),
다른 해결 방안을 고민해봄이 어떠할지?

2021-11-22 14:31 UTC, jeekim2 commented on LHM/Problems/beakjoon/2577.py
> +A = int(input())
문제 주소 주석 삽입 필요

2021-11-22 14:37 UTC, jeekim2 requested changes
파일 위치&이름 포맷 맞추길

2021-11-22 14:37 UTC, jeekim2 commented on LHM/Problems/beakjoon/1152.py
> +print(cnt+1)
결국 이게 통과하냐 안하냐로 되면 모로 가도 서울만 가면 되니까 Pass 가 나오긴 할텐데,
원칙적으로 보면 이건 공백의 갯수+1을 구한것이지 "단어"를 판별하고 그 갯수를 세아린게 아니지 않나 싶음.
공부 차원에서 보자면 좀 더 원칙적일 필요가 있지 않을까 하는 개인적인 생각.

2021-11-23 14:34 UTC, jeekim2 approved these changes
기존 리뷰 내용은 확인 한번 해보셔

2021-11-23 14:40 UTC, hongmyeong-lee commented on LHM/Problems/beakjoon/1110.py
> +in1 = math.floor(inputVal/10)
OK

2021-11-23 14:44 UTC, hongmyeong-lee commented on LHM/Problems/beakjoon/10951.py
> +    a, b = map(int, sys.stdin.readline().split())
넹 input만쓰면 error 뜨고 문제보면 애초에 sys 쓰라고 나와있어요

2021-11-23 14:49 UTC, hongmyeong-lee commented on LHM/Problems/beakjoon/1110.py
> +#https://www.acmicpc.net/problem/1110
맞긴 함

2021-11-24 06:57 UTC, Bobzzang approved these changes
유첨 내용 참조하여 주시고, 도움이 되겠다 싶은 부분은 적용 고고!

2021-11-24 06:57 UTC, Bobzzang commented on LHM/Problems/beakjoon/10818.py
> +    input_val.append(input())
백준 문제에서 언급된 input 형태가 아닌거 같습니다.
하나씩 중첩하는 것이 아닌 한번에 List Array를 주는 것을 Input으로 정의하고 있어 보입니다.

아래 내용도 한번 검토해주세요!

```suggestion
    input_val = list(map(int,input().split()))
```

2021-11-24 06:57 UTC, Bobzzang commented on LHM/Problems/beakjoon/10818.py
> +        min = input_val[i]
이렇게 간략하게 사용하는 것도 가능한 방법일거 같습니다.

for에 대한 사용 방법이 C와 다르게 input_val 안에 있는 정보를 다 사용하는 동안으로 바로 읽어올 수 있습니다.
(index에 맞춰 불러오지 않고, 간략하게 사용가능함.)

```suggestion
for val in input_val:
    if val > max:
        max = val
    if val < min:
        min = val
```

2021-11-24 12:18 UTC, YHsla commented on LHM/Problems/beakjoon/10818.py
> +    input_val.append(input())
아니면 list의 extend 함수 사용해서 input을 list로 담는 방법도 괜찮을 듯?

2021-11-24 12:18 UTC, YHsla commented on LHM/Problems/beakjoon/10818.py
> +for i in range(0,N):
굳이 range(0,N) 표현할 필요 없을 듯 : range(N)

2021-11-24 12:18 UTC, YHsla commented on LHM/Problems/beakjoon/10818.py
> +        min = input_val[i]
문제에 "서로 다른 N개"라는 표현이 없으니 Min, Max 비교 시 등호(=)도 고려 필요해보임

2021-11-24 12:18 UTC, YHsla commented on LHM/Problems/beakjoon/1110.py
> +input.insert(1,in2) #6
내 생각에도 값을 갖고 있는 List에 추가로 넣는 것이 아니면 append가 더 적절해 보임

2021-11-24 12:55 UTC, merged