5086 lhm
HL-Cledor/algoStudy pull request #83
Opened 2022-01-01 02:38 UTC by hongmyeong-lee

2022-01-01 14:49 UTC, jeekim2 requested changes
1. #67 에서의 리뷰 주안점에 대해 Feedback 바람. 11650과 2750 또한 이 연장선에 있다고 생각 (정렬 구현 문제인데, sort로 풀어버리면...)
2. Programmers 문제 파일 이동 시 폴더명 변경 요청 (Issue에 예시 참조)

2022-01-03 12:14 UTC, hongmyeong-lee commented
2750은 pull request 새로 해서 올렸고 11650도 sort 안쓰고 풀었는데 시간 초과가 뜨네요..

2022-01-05 08:32 UTC, jeekim2 commented
#65 와 마찬가지로, 해결이 안된 문제이니 draft 처리함 (앞으로는 직접해)
재현이 PR에 가이드 하는대로, 덜풀린 문제를 따로 PR 만들고, 이 PR에서는 해당 문제 삭제 commit을 만든 후
merge부터 진행해도 무방.

2022-01-06 13:53 UTC, hongmyeong-lee commented
이거 문제 통과하고 11650,2750도 했는데 왜 draft 해놓은거에요?

2022-01-06 14:55 UTC, jeekim2 commented
> 이거 문제 통과하고 11650,2750도 했는데 왜 draft 해놓은거에요?

11650 오늘 했잖음

2022-01-06 14:56 UTC, jeekim2 submitted a review, later dismissed

2022-01-14 11:39 UTC, BitnuriKim submitted a review, later dismissed

2022-01-14 12:38 UTC, hongmyeong-lee commented
다시 올렸는데 한번만 다시 부탁드립니다.

2022-01-14 13:35 UTC, jeekim2 approved these changes

2022-01-17 13:46 UTC, YHsla approved these changes

2022-01-18 09:27 UTC, merged