YYH - Problem 1316
HL-Cledor/algoStudy pull request #84
Opened 2022-01-02 06:08 UTC by YHsla

2022-01-05 08:36 UTC, jeekim2 requested changes
YH1은 안풀리는 풀이로 보이는데, 명확한 표시 부탁.
파일 이름을 변경하는게 가장 명확할 것 같다는 의견.

2022-01-05 08:49 UTC, jeekim2 requested changes

2022-01-05 08:49 UTC, jeekim2 commented on Problems/1316/ans_1316_YH1.py
> +#다른 풀이보니까 dictionary로 풀어버리네... 2번째 풀이로 따라해보겠음
아래 답안이 잘 된다는건지 아니라는건지 모르겠는 주석. 정리요

2022-01-05 08:49 UTC, jeekim2 commented on Problems/1316/ans_1316_YH1.py
> +        char_list.append(input().rstrip())
input 함수를 sys.stdin.readline 으로 overriding 하지 않았다면,
12번줄에서 rstrip을 안써도 됐을 것.
N max 가 100밖에 안되니 굳이 overriding이 필요했을까 싶네.

2022-01-05 08:49 UTC, jeekim2 commented on Problems/1316/ans_1316_YH1.py
> +    for char in char_list:
변수이름이 별로...
이름이 char인데 내용은 string

2022-01-05 08:49 UTC, jeekim2 commented on Problems/1316/ans_1316_YH1.py
> +                if char[i] != char[i+1] and char[i] in char[i+2:]:
띄엄띄엄 중복문자 찾는 발상은 좋았는데, char[i] in char[i+2]에서 어쨋건 탐색 시간이 걸림에 주의

2022-01-05 13:33 UTC, YHsla commented on Problems/1316/ans_1316_YH1.py
> +#다른 풀이보니까 dictionary로 풀어버리네... 2번째 풀이로 따라해보겠음
문제 풀면서 그냥 느낀 생각들을 적은거라 무시하셔도 됩니다.
향후엔 그런 주석들은 삭제 후 올리겠습니다

2022-01-05 13:33 UTC, YHsla commented on Problems/1316/ans_1316_YH1.py
> +        char_list.append(input().rstrip())
횟수 상관 없이 sys.stdin.readline이 input 대비 가벼워서 계속 그렇게 쓰고 있는데,
횟수도 고려해서 적절하게 사용해보겠습니다~

2022-01-05 13:33 UTC, YHsla commented on Problems/1316/ans_1316_YH1.py
> +                if char[i] != char[i+1] and char[i] in char[i+2:]:
YES

2022-01-05 13:35 UTC, YHsla commented
@jeekim2 YH2도 정상 풀이입니다. Dictionary 이용한 풀이이며, 문제 Fail의 경우는 draft로 올리던가 함수 명에 표시하는 방향으로 하고 있어요.

2022-01-06 10:00 UTC, jeekim2 commented
> @jeekim2 YH2도 정상 풀이입니다. Dictionary 이용한 풀이이며, 문제 Fail의 경우는 draft로 올리던가 함수 명에 표시하는 방향으로 하고 있어요.

틀렸다고 나옴

2022-01-07 12:48 UTC, hongmyeong-lee commented on Problems/1316/ans_1316_YH1.py
> +        char.append(input().rstrip())
r strip을 쓴 이유가 뭐에요?

2022-01-07 12:48 UTC, hongmyeong-lee commented on Problems/1316/ans_1316_YH1.py
> +            if temp > 1 and c[i] != c[i+temp-1]:
이부분은 중복된 문자가 있다고 했을때 문자를 구분하는 부분인거 같네요

2022-01-12 14:20 UTC, YHsla commented
#116 으로 CR 반영했습니다...

2022-01-16 08:54 UTC, YHsla commented
#116 으로 대체

2022-01-16 08:54 UTC, closed without merging