1037 lhm
HL-Cledor/algoStudy pull request #85
Opened 2022-01-02 09:22 UTC by hongmyeong-lee

2022-01-02 11:42 UTC, jeekim2 requested changes
이것도 예전 commit이 섞여있고, #67 에 얘기한 내용의 feedback 없으며 해당 반영 또한 없으므로 CR 처리

2022-01-03 09:13 UTC, hongmyeong-lee commented
#67 반영했으니 이것도 풀어주세요 
이전에 말했던 sort() 를 안쓰는 방향? 이거는 sort 안쓰고 min, max 로 처리해도 풀 수 있음
min/max 구현하는 건 별로 안어려우니 pass 해도 될듯

2022-01-03 10:59 UTC, hongmyeong-lee commented
그리고 보니까 2750은 pull request안보여서 새로 만들어서 해야겠네요

2022-01-03 14:06 UTC, jeekim2 commented
> #67 반영했으니 이것도 풀어주세요
> 이전에 말했던 sort() 를 안쓰는 방향? 이거는 sort 안쓰고 min, max 로 처리해도 풀 수 있음
> min/max 구현하는 건 별로 안어려우니 pass 해도 될듯

이 PR에 반영된 내용이 없는데?
commit이 중복되므로 반영한 PR이 있으면 해당 PR이 뭔지 남기고, 이 PR은 닫아버리는 것도 방법.

2022-01-04 11:39 UTC, jeekim2 approved these changes

2022-01-11 09:23 UTC, Bobzzang approved these changes
간단한 문제라 리뷰가 쉽구만요...Approve 합니다

2022-01-11 12:41 UTC, merged